<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	 <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Application\DTOs\" />
    <Folder Include="Application\Validation\" />
    <Folder Include="Application\Services\" />
    <Folder Include="Domain\Enum\" />
    <Folder Include="Domain\ValueObjects\" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />		
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
	</ItemGroup>

</Project>
