// <auto-generated />
using System;
using Barbearia.Core.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarbeariaInfrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Barbearia.Core.Domain.Entities.Avaliacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("horario");

                    b.Property<int>("IdBarbeiro")
                        .HasColumnType("integer")
                        .HasColumnName("id_barbeiro");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdHorario")
                        .HasColumnType("integer")
                        .HasColumnName("id_horario");

                    b.Property<int>("IdServico")
                        .HasColumnType("integer")
                        .HasColumnName("id_servico");

                    b.Property<int>("Nota")
                        .HasColumnType("integer")
                        .HasColumnName("nota");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdHorario")
                        .IsUnique()
                        .HasDatabaseName("ux_comentarios_horario");

                    b.HasIndex("IdServico");

                    b.HasIndex("IdBarbeiro", "Horario")
                        .HasDatabaseName("ix_comentarios_barbeiro_horario");

                    b.ToTable("comentarios", (string)null);
                });

            modelBuilder.Entity("Barbearia.Core.Domain.Entities.Barbeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("especialidade");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ux_barbeiro_usuario");

                    b.ToTable("barbeiro", (string)null);
                });

            modelBuilder.Entity("Barbearia.Core.Domain.Entities.Horarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Horario")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("horario");

                    b.Property<int>("Id_barbeiro")
                        .HasColumnType("integer")
                        .HasColumnName("id_barbeiro");

                    b.Property<int>("Id_cliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("Id_servico")
                        .HasColumnType("integer")
                        .HasColumnName("id_servico");

                    b.Property<int>("StatusAgendamento")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Id_servico");

                    b.HasIndex("Id_barbeiro", "Horario", "StatusAgendamento")
                        .HasDatabaseName("ix_horarios_barbeiro_horario_status");

                    b.HasIndex("Id_cliente", "StatusAgendamento", "Horario")
                        .HasDatabaseName("ix_horarios_cliente_status_horario");

                    b.ToTable("horarios", (string)null);
                });

            modelBuilder.Entity("Barbearia.Core.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEM")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("ExpiraEM")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expira_em");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<bool>("Revogado")
                        .HasColumnType("boolean")
                        .HasColumnName("revogado");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_token_token");

                    b.HasIndex("Id_usuario", "Revogado", "ExpiraEM")
                        .HasDatabaseName("ix_refresh_token_usuario_revogado_expira");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("Barbearia.Core.Domain.Entities.Servicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("Duracao")
                        .HasColumnType("integer")
                        .HasColumnName("duracao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.HasIndex("Ativo", "Nome")
                        .HasDatabaseName("ix_servicos_ativo_nome");

                    b.ToTable("servicos", (string)null);
                });

            modelBuilder.Entity("Barbearia.Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativado")
                        .HasColumnType("boolean")
                        .HasColumnName("ativado");

                    b.Property<DateTime?>("BloqueioAte")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("bloqueioate");

                    b.Property<DateTime?>("CodigoRecuperacaoExpiraEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tempocodigo");

                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<bool>("CodigoAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("codigovalido");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nome");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<int>("TentativasCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativascodigo");

                    b.Property<int>("TentativasLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativaslogin");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_login");

                    b.HasIndex("Ativado", "Role")
                        .HasDatabaseName("ix_usuario_ativado_tipo");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Barbearia.Core.Domain.Entities.Avaliacoes", b =>
                {
                    b.HasOne("Barbearia.Core.Domain.Entities.Barbeiro", "BarbeiroF")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("IdBarbeiro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Barbearia.Core.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Barbearia.Core.Domain.Entities.Horarios", null)
                        .WithOne()
                        .HasForeignKey("Barbearia.Core.Domain.Entities.Avaliacoes", "IdHorario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Barbearia.Core.Domain.Entities.Servicos", null)
                        .WithMany()
                        .HasForeignKey("IdServico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BarbeiroF");
                });

            modelBuilder.Entity("Barbearia.Core.Domain.Entities.Barbeiro", b =>
                {
                    b.HasOne("Barbearia.Core.Domain.Entities.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Barbearia.Core.Domain.Entities.Barbeiro", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Barbearia.Core.Domain.Entities.Horarios", b =>
                {
                    b.HasOne("Barbearia.Core.Domain.Entities.Barbeiro", "Barbeiro")
                        .WithMany()
                        .HasForeignKey("Id_barbeiro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Barbearia.Core.Domain.Entities.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("Id_cliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Barbearia.Core.Domain.Entities.Servicos", "Servicos")
                        .WithMany()
                        .HasForeignKey("Id_servico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barbeiro");

                    b.Navigation("Cliente");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("Barbearia.Core.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Barbearia.Core.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Barbearia.Core.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("Barbearia.Core.Domain.ValueObjects.Cpf", "CPF", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("integer");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("cpf");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Numero")
                                .IsUnique()
                                .HasDatabaseName("ux_usuario_cpf");

                            b1.ToTable("usuario");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Barbearia.Core.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("integer");

                            b1.Property<string>("EmailPessoa")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("EmailPessoa")
                                .IsUnique()
                                .HasDatabaseName("ux_usuario_email");

                            b1.ToTable("usuario");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Barbearia.Core.Domain.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("integer");

                            b1.Property<string>("Telefone")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("numero");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Telefone")
                                .IsUnique()
                                .HasDatabaseName("ux_usuario_telefone");

                            b1.ToTable("usuario");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Barbearia.Core.Domain.ValueObjects.Senha", "Senha", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("integer");

                            b1.Property<string>("SenhaHash")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("senha");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("usuario");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("Senha")
                        .IsRequired();
                });

            modelBuilder.Entity("Barbearia.Core.Domain.Entities.Barbeiro", b =>
                {
                    b.Navigation("Avaliacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
