FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore BarbeariaApi/BarbeariaApi.csproj

RUN dotnet publish BarbeariaApi/BarbeariaApi.csproj \
    -c Release \
    -o /app/publish \
    --no-restore


FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_ENVIRONMENT=Production

EXPOSE 80

CMD ["sh", "-c", "dotnet BarbeariaApi.dll --urls http://0.0.0.0:${PORT:-80}"]