<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BarbeariaCore\BarbeariaCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Configuration\" />
    <Folder Include="Data\DatabaseErrors\Abstractions\" />
    <Folder Include="Security\" />
    <Folder Include="Repository\" />
  </ItemGroup>

	<ItemGroup>

		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.13" />
	</ItemGroup>

  <PropertyGroup>
	 <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>

